---
- name: 'Reload nfs'
  ansible.builtin.service:
    name: "{{ nfs_server_service }}"
    state: 'restarted'
  loop: "{{ nfs_server_service_list }}"
  loop_control:
    loop_var: 'nfs_server_service'

- name: 'Reload exports'
  ansible.builtin.command: /usr/sbin/exportfs -ar
  changed_when: true

- name: 'Remount filesystems'
  ansible.posix.mount:
    path: "{{ quota_mount['mountpoint'] }}"
    state: 'remounted'
  loop: "{{ nfs_server_quota_filesystems }}"
  loop_control:
    loop_var: 'quota_mount'
